apiVersion: apps/v1
kind: Deployment
metadata:
  name: jdeployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demoApp
    spec:
      containers:
        - name: jenkinsmaster
          image: jenkins/jenkins:lts
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      nodeSelector:
        disktype: work1
      volumes:
        - name: jenkins-home
          emptyDir: {}
  selector:
    matchLabels:
      app: demoApp