apiVersion: v1
kind: PersistentVolume
metadata:
  name: opspv000
  namespace: kube-jenkins-test
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/data/k8s"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: opspvc000
  namespace: kube-jenkins-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi